                                    <div class="grid_8 t_a_bottom">
                                                <?php foreach ($this->comments as $comment) : ?>
                                                <div class="clearfix t_a_ui_data_list_content">
                                                        <div class="grid_4 alpha">
                                                            <?php echo $comment->remark; ?>
                                                        </div>

                                                        <div class="grid_2"><?php echo $this->user()->getUserByName($comment->by_id); ?></div>

                                                        <div class="grid_2 omega"><?php echo $comment->comment_date; ?></div>
                                                </div>
                                                <?php endforeach; ?>
                                    </div>
                                    <div class="grid_8 t_a_bottom"><hr /></div>
                                    <div class="grid_8 t_a_bottom">
                                            <div class="prefix_1 suffix_1" id="RemarkContainer">
                                                    <div class="clearfix t_a_bottom">
                                                            <label>Remark:</label>
                                                            <textarea style="width: 200px" name="remark" id="remark">
                                                            </textarea>
                                                    </div>

                                                    <hr />

                                                    <div class="clearfix t_a_bottom">
                                                            <label>&nbsp;</label>
                                                            <button type="submit" id="addCommentButton"><span>Add Comment</span></button>
                                                    </div>
                                            </div>
                                    </div>