<div class="prefix_1 suffix_1" id="PersonalInfoContainer">
                                        <input type="hidden" name="emp_id" value="<?php echo $this->employee->emp_id; ?>" />
                                        <div class="clearfix t_a_bottom">
                                                <label>Surname:</label>
                                                <input type="text" id="surname" name="surname" style="width: 200px" value="<?php echo $this->employee->surname; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Other Names:</label>
                                                <input type="text" id="surname" name="other_name" style="width: 200px" value="<?php echo $this->employee->other_name; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Department:</label>
                                                <select name="dept_id">
                                                    <?php foreach($this->departments as $department) { ?>
                                                    <option value="<?php $department->dept_id?>"
                                                    <?php if($department->dept_id == $this->employee->dept_id) {echo ' selected="selected"';}?>
                                                    ><?php echo $department->name; ?></option>
                                                    <?php } ?>
                                                </select>
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Job Title:</label>
                                                <select name="job_title">
                                                    <?php foreach($this->job_titles as $job_title) { ?>
                                                    <option value="<?php echo $job_title->id?>"
                                                    <?php if($job_title->id == $this->employee->job_title) {echo ' selected="selected"';}?>
                                                    ><?php echo $job_title->name; ?></option>
                                                    <?php } ?>
                                                </select>
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Job Group:</label>
                                                <select name="job_group">
                                                    <?php foreach($this->job_groups as $job_group) { ?>
                                                    <option value="<?php $job_group->id?>"
                                                    <?php if($job_group->id == $this->employee->job_group) {echo ' selected="selected"';}?>
                                                    ><?php echo $job_group->name; ?></option>
                                                    <?php } ?>
                                                </select>
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Gender:</label>
                                                <select name="gender">
                                                    <option value="<?php echo $this->employee->gender;?>"><?php echo $this->employee->gender;?></option>
                                                    <option value="Male">Male</option>
                                                    <option value="Female">Female</option>
                                                </select>
                                        </div>

                                        <hr />

                                         <div class="clearfix t_a_bottom">
                                                <label>Contact Cell:</label>
                                                <input type="text" id="contact_cell" name="contact_cell" style="width: 200px" value="<?php echo $this->employee->contact_cell; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>National ID No:</label>
                                                <input type="text" id="national_id_no" name="national_id_no" style="width: 200px" value="<?php echo $this->employee->national_id_no; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Passport No:</label>
                                                <input type="text" id="passport_no" name="passport_no" style="width: 200px" value="<?php echo $this->employee->passport_no; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Address:</label>
                                                <textarea name="address">
                                                    <?php echo $this->employee->address; ?>
                                                </textarea>
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>County:</label>
                                                <input type="text" id="county" name="county" style="width: 200px" value="<?php echo $this->employee->county; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Location:</label>
                                                <input type="text" id="location" name="location" style="width: 200px" value="<?php echo $this->employee->location; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Village / Address:</label>
                                                <input type="text" id="village_estate" name="village_estate" style="width: 200px" value="<?php echo $this->employee->village_estate; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Emergency Contact:</label>
                                                <input type="text" id="contact_person" name="contact_person" style="width: 200px" value="<?php echo $this->employee->contact_person; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>Contact Person No:</label>
                                                <input type="text" id="contact_person_no" name="contact_person_no" style="width: 200px" value="<?php echo $this->employee->contact_person_no; ?>" />
                                        </div>

                                        <hr />

                                        <div class="clearfix t_a_bottom">
                                                <label>&nbsp;</label>
                                                <?php echo $this->tokenElement; ?>
                                                <button type="submit" id="savePersonalInfo"><span>Save Changes</span></button>
                                        </div>


</div>
<script type="text/javascript">


$(document).ready(function() {
        /**
	 * Create tabs
	 */
	$('#cacheTabs').tabs();

	$('a.collapseAction').click(function() {
		$('#tagRow_' + $(this).attr('id')).toggle();
	});

        $('#addCommentButton').click(function() {
		var query = {
			remark: $('#RemarkContainer').find('textarea[name="remark"]').attr('value')
		};
		QueryComments(query);
	});


        $('#saveInfo').click(function() {
		var query = {
			surname: $('#PersonalInfoContainer').find('input[name="surname"]').attr('value'),
                        other_name: $('#PersonalInfoContainer').find('input[name="other_name"]').attr('value'),
                        dept_id: $('#PersonalInfoContainer').find('select[name="dept_id"]:first').attr('value'),
                        job_group: $('#PersonalInfoContainer').find('select[name="job_group"]:first').attr('value'),
                        gender: $('#PersonalInfoContainer').find('select[name="gender"]:first').attr('value'),
                        contact_cell: $('#PersonalInfoContainer').find('input[name="contact_cell"]').attr('value'),
                        address: $('#PersonalInfoContainer').find('textarea[name="address"]').attr('value'),
                        county: $('#PersonalInfoContainer').find('input[name="county"]').attr('value'),
                        location: $('#PersonalInfoContainer').find('input[name="location"]').attr('value'),
                        village_estate: $('#PersonalInfoContainer').find('input[name="village_estate"]').attr('value'),
                        contact_person: $('#PersonalInfoContainer').find('input[name="contact_person"]').attr('value'),
                        contact_person_no: $('#PersonalInfoContainer').find('input[name="contact_person_no"]').attr('value'),
                        national_id_no: $('#PersonalInfoContainer').find('input[name="national_id_no"]').attr('value'),
                        passport_no: $('#PersonalInfoContainer').find('input[name="passport_no"]').attr('value')
		};
		savePersonalDetails(query);
	});
});

function QueryComments(query) {
	$('#comments').html('').addClass('t_a_ui_helper_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array('controller'=>'employee', 'action'=>'add-comment')); ?>',
		type: 'POST',
		data: { query: $.toJSON(query) },
		success: function(response) {
			$('#comments').html(response).removeClass('t_a_ui_helper_loading').fadeIn('normal');
		}
	});
 };

function savePersonalDetails(query) {
	$('#EmpInfo').html('').addClass('t_a_ui_helper_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array('controller'=>'employee', 'action'=>'update-personal-info')); ?>',
		type: 'POST',
		data: { query: $.toJSON(query) },
		success: function(response) {
			$('#EmpInfo').html(response).removeClass('t_a_ui_helper_loading').fadeIn('normal');
		}
	});
}
</script>