<?php

$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">	
	<span>Generate Payslips</span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('controller'=>'report', 'action'=>'generate-payslips')); ?>" id="addJObGroupForm">
<div class="grid_12 t_a_bottom">Enter the user information in the form:</div>

<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		<div class="clearfix t_a_bottom">
			<label>Month:</label>
			<select name="month">
                            <option value="1">January</option>
                            <option value="2">February</option>
                            <option value="3">March</option>
                            <option value="4">April</option>
                            <option value="5">May</option>
                            <option value="6">June</option>
                            <option value="7">July</option>
                            <option value="8">August</option>
                            <option value="9">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>
                        </select>
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>Year:</label>
			<select name="year">
                            <option value="2011">2011</option>
                            <option value="2012">2012</option>
                        </select>
		</div>

		<hr />

		
		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="submit"><span>Generate Pay Slips</span></button>
		</div>
	</div>
</div>
</form>
