<?php

$this->headLink()
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.core.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.resizable.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.dialog.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.theme.css'));

$this->headScript()
	->appendFile($this->staticUrl('/js/jquery.ui/ui.core.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.draggable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.resizable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.dialog.js'))
	->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span>List of Deductions</span>
</div>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<?php if ($this->deductions) : ?>
<div class="grid_12 t_a_bottom">
    <div class="grid_9 alpha">Listing of Job Deductions below:<br /> You can use the filter form to get deductions for a particular Job group</div>

<div class="grid_3 omega">
	<div class="t_a_right">
		<a href="<?php echo $this->url(array('controller'=>'deduction', 'action'=>'add')); ?>" class="t_a_ui_button_link"><span>Add New Deduction</span></a>
	</div>
</div>
</div>
<!-- Filter form -->
<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1" id="filerContainer">
		<div class="clearfix t_a_bottom">
			<div class="grid_5 alpha">
				<label>Job Group:</label>
				<select name="job_group" style="width: 180px">
					<option value="">---</option>
					<?php foreach ($this->job_groups as $job_group) : ?>
					<option value="<?php echo $job_group->id; ?>"><?php echo $job_group->name; ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="button" id="filterButton"><span>Filter</span></button>
		</div>
	</div>
</div>

<div class="grid_12 t_a_ui_data_list_header">
	<div class="grid_2 alpha">
		<div>Name</div>
	</div>

	<div class="grid_4">Description</div>

        <div class="grid_2">Amount</div>

	<div class="grid_1">Status</div>	

        <div class="grid_2">Job Group</div>

</div>

<div class="grid_12 t_a_bottom">
    <div id="deductions">
        <?php foreach ($this->deductions as $deduction) : ?>
	<div class="clearfix t_a_ui_data_list_content" id="roleRow_<?php echo $benefit->id; ?>">
		<div class="grid_2 alpha">
			<div><?php echo $deduction->name; ?></div>

			<div class="t_a_top t_a_ui_helper_action">
				<a class="lockAction" rel="<?php echo $deduction->id; ?>_<?php echo $deduction->is_active; ?>_<?php echo $deduction->name; ?>" href="javascript: void(0);"><?php if ($deduction->is_active) : ?>Unlock<?php else : ?>Lock<?php endif; ?></a>
				<?php  if (!$deduction->is_active) : ?> | <a class="editAction" href="/deduction/update/id/<?php echo $deduction->id; ?>">Edit</a> | <a class="deleteAction" rel="<?php echo $deduction->id; ?>_<?php echo $deduction->name; ?>" href="javascript: void(0);">Delete</a><?php endif; ?>
			</div>
		</div>

		<div class="grid_4"><?php echo $deduction->description; ?>&nbsp;</div>

                <div class="grid_2">Ksh <?php echo $deduction->amount; ?></div>

		<div class="grid_1"><?php if ($deduction->is_active) : ?>Locked<?php else : ?>Unlocked<?php endif; ?></div>

                <div class="grid_2"><?php echo $this->jobGroup()->getJobGroupName($deduction->job_group); ?></div>
	</div>
	<?php endforeach; ?>
    </div>	
</div>
<?php endif; ?>

<div id="messageDialog"></div>

<div id="confirmDialog"></div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#filterButton').click(function() {
		var query = {
		job_group: $('#filerContainer').find('select[name="job_group"]:first').attr('value')
		};
		filterDeductions(query);
	});
        
	$('a.lockAction').click(function() {
		var self = this;
		var arr = $(this).attr('rel').split('_');
		$(self).html('').addClass('t_a_ui_helper_loading');
		$.ajaxq('core_role', {
			url: '<?php echo $this->url(array('controller'=>'deduction', 'action'=>'lock')); ?>',
			type: 'POST',
			data: { id: arr[0], lock: arr[1] },
			success: function(response) {
				$(self).attr('rel', arr[0] + '_' + response + '_' + arr[2]);
				if (response == 1) {
					$(self).html("Unlock");
				} else {
					$(self).html("Lock");
				}
				$(self).removeClass('t_a_ui_helper_loading');
				$('#messageDialog').html((response == 1) ? sprintf('<?php echo addslashes("Deduction has been locked"); ?>', arr[2]) : sprintf('<?php echo addslashes("Deduction has been unlocked"); ?>', arr[2]))
					.dialog({
						title: '<?php echo addslashes("Notification"); ?>',
						dialogClass: 't_a_ui_dialog',
						modal: true,
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
			}
		});
	});


	$('a.deleteAction').click(function() {
		var self = this;
		$('#confirmDialog').html('<?php echo addslashes("Are you sure you want to delete this Deduction?"); ?>')
			.dialog({
				title: '<?php echo addslashes("Confirm delete"); ?>',
				dialogClass: 't_a_ui_dialog',
				modal: true,
				closeOnEscape: false,
				resizable: false,
				open: function(event, ui) {
					$('.ui-dialog-titlebar-close').hide();
					$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
				},
				buttons: {
					'<?php echo addslashes("No"); ?>': function() {
						$(this).dialog('destroy');
					},
					'<?php echo addslashes("Yes"); ?>': function() {
						$(this).dialog('destroy');
						$(self).html('&nbsp;').addClass('t_a_ui_helper_loading').css('text-decoration', 'none');
						var arr = $(self).attr('rel').split('_');
						$.ajaxq('core_role', {
							url: '<?php echo $this->url(array('controller'=>'deduction', 'action'=>'delete')); ?>',
							type: 'POST',
							data: { id: arr[0] },
							success: function(response) {
								$('#roleRow_' + arr[0]).fadeOut('slow');
								$('#messageDialog').html(sprintf('<?php echo addslashes("Deduction was successfully deleted"); ?>', arr[1]))
									.dialog({
										title: '<?php echo addslashes("Notification"); ?>',
										dialogClass: 't_a_ui_dialog',
										modal: true,
								    	show: { effect: 'fade' },
										open: function(event, ui) {
											setTimeout(function() {
												$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											}, 3000);
										}
									});
							}
						});
					}
				}
			});
	});
        

});

function filterDeductions(query) {
	$('#benefits').html('').addClass('t_a_ui_helper_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array('controller'=>'deduction', 'action'=>'list')); ?>',
		type: 'POST',
		data: { query: $.toJSON(query) },
		success: function(response) {
			$('#deductions').html(response).removeClass('t_a_ui_helper_loading').fadeIn('normal');
		}
	});
};
</script>
