<?php

$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">	
	<span>Run Payroll</span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('controller'=>'payroll', 'action'=>'run')); ?>" id="addJobTitleForm">
<div class="grid_12 t_a_bottom">Close this Pay Period. Any other details will be entered into the coming period</div>

<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		
		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="submit" name="confirm"><span>CONFIRM RUN PAYROLL</span></button>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#addJobTitleForm').validate({
		rules: {
			name: {
				required: true
			},
			description: {
				required: true
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo addslashes("The job title name is required"); ?>"
			},
			description: {
	        	required: "<?php echo addslashes("The job title description is required"); ?>"
			}
		}
	});
});
</script>
