<?php

$this->headLink()
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.core.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.resizable.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.dialog.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.theme.css'));

$this->headScript()
	->appendFile($this->staticUrl('/js/jquery.ui/ui.core.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.draggable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.resizable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.dialog.js'))
	->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span>Banks</span>
</div>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>
<?php if ($this->banks) : ?>
<div class="grid_12 t_a_bottom">
    The Banks are listed as follows.<br>
</div>

<div class="grid_12 t_a_ui_data_list_header">
	<div class="grid_7 alpha">
		<div>Bank Name</div>
	</div>
        <div class="grid_5 omega"></div>

</div>

<div class="grid_12 t_a_bottom">
	<?php foreach ($this->banks as $bank) : ?>
	<div class="clearfix t_a_ui_data_list_content" id="roleRow_<?php echo $bank->id; ?>">
		<div class="grid_7 alpha">
			<?php echo $bank->name;  ?>		
		</div>

            <div class="grid_5 omega">
                <a class="editAction" href="/bank/update/id/<?php echo $bank->id; ?>">Edit</a>
				| <a class="deleteAction" rel="<?php echo $bank->id; ?>_<?php echo $bank->name; ?>" href="javascript: void(0);">Delete</a>
            </div>

	</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>

<div class="grid_12 t_a_bottom">
	<h3>Add New Bank</h3>
</div>

<div class="grid_12 t_a_bottom"><hr /></div>

<form method="post" id="addBankForm" name="addBankForm" action="<?php echo $this->url(array('controller'=>'bank', 'action'=>'add')); ?>">
<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		<div class="clearfix t_a_bottom">
			<label>Bank Name:</label>
			<input type="text" style="width: 200px" name="name" id="name" />
		</div>
		
                <hr />

		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="submit"><span>Create</span></button>
		</div>
	</div>
</div>
</form>

<div id="messageDialog"></div>

<div id="confirmDialog"></div>

<script type="text/javascript">
    $(document).ready(function() {
	$('a.deleteAction').click(function() {
		var self = this;
		$('#confirmDialog').html('<?php echo addslashes("Are you sure you want to delete this Bank?"); ?>')
			.dialog({
				title: '<?php echo addslashes("Confirm"); ?>',
				dialogClass: 't_a_ui_dialog',
				modal: true,
				closeOnEscape: false,
				resizable: false,
				open: function(event, ui) {
					$('.ui-dialog-titlebar-close').hide();
					$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
				},
				buttons: {
					'<?php echo addslashes("No"); ?>': function() {
						$(this).dialog('destroy');
					},
					'<?php echo addslashes("Yes"); ?>': function() {
						$(this).dialog('destroy');
						$(self).html('&nbsp;').addClass('t_a_ui_helper_loading').css('text-decoration', 'none');
						var arr = $(self).attr('rel').split('_');
						$.ajaxq('core_role', {
							url: '<?php echo $this->url(array('controller'=>'bank', 'action'=>'delete')); ?>',
							type: 'POST',
							data: { id: arr[0] },
							success: function(response) {
								$('#roleRow_' + arr[0]).fadeOut('slow');
								$('#messageDialog').html(sprintf('<?php echo addslashes("Bank was successfully deleted"); ?>', arr[1]))
									.dialog({
										title: '<?php echo addslashes("Notification"); ?>',
										dialogClass: 't_a_ui_dialog',
										modal: true,
								    	show: { effect: 'fade' },
										open: function(event, ui) {
											setTimeout(function() {
												$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											}, 3000);
										}
									});
							}
						});
					}
				}
			});
	});


	/**
	 * Validate form
	 */
	$('#addBankForm').validate({
		rules: {
			name: {
				required: true
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo addslashes("The bank name is required"); ?>"
			}
		}
	});
});
</script>
