<?php

$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span><a href="<?php echo $this->url(array('controller'=>'bank', 'action'=>'list')); ?>">List of Banks</a></span>
	<span>Edit Bank</span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('controller'=>'bank', 'action'=>'update')); ?>" id="editBankForm">
<div class="grid_12 t_a_bottom">Enter the Bank information in the form:</div>

<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
                <input type="hidden" name="id" value="<?php echo $this->bank->id; ?>" />
		<div class="clearfix t_a_bottom">
			<label>Bank Name:</label>
			<input type="text" style="width: 200px" name="name" id="name" value="<?php echo $this->bank->name; ?>"/>
		</div>

		<hr />	

		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
                        <button type="submit"><span>Save Changes</span></button> or <a href="<?php echo $this->url(array('controller'=>'bank', 'action'=>'list'), null, true)?>">Cancel</a>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#editBankForm').validate({
		rules: {
			name: {
				required: true
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo addslashes("The bank name is required"); ?>"
			}
		}
	});

});
</script>
