<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>    
    <meta name="robots" content="noindex, nofollow" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->staticUrl('/images/favicon.ico') ?>" />
    
	<?php
    $this->headLink()
	->prependStylesheet($this->staticUrl('/css/960/all.min.css'))
    	->appendStylesheet($this->staticUrl('/css/admin.css'))
    	->appendStylesheet($this->staticUrl('/css/admin-ie.css'), 'screen', 'lte IE 7');

    $this->headScript()
    	->prependFile($this->staticUrl('/js/openhr/namespace.js'))
    	->prependFile($this->staticUrl('/js/jquery/jquery.min.js'))
    	->appendFile($this->staticUrl('/js/jquery.ajaxq/jquery.ajaxq.min.js'))
    	->appendFile($this->staticUrl('/js/jquery.json/jquery.json.min.js'));
    
    ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headLink(); ?>
</head>
<body id="t_a_auth">
	<!-- Content -->
	<div id="t_a_body_wrapper" class="container_12">
		<div id="t_a_auth_container">
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
	
	<div class="clear"></div>
    
    <!-- Footer -->
    <div id="t_a_auth_footer">
      	<div>Powered by <a href="www.openhrms.net">OpenHRMS</a> version 1.0</div>
    </div>
</body>
</html>
