<?php

$this->headLink()
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.core.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.resizable.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.dialog.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.theme.css'));

$this->headScript()
	->appendFile($this->staticUrl('/js/jquery.ui/ui.core.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.draggable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.resizable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.dialog.js'))
	->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span>List of Departments</span>
</div>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<?php if ($this->departments) : ?>
<div class="grid_12 t_a_bottom">
    The departments are listed as follows.<br>You can NOT remove a department if it is locked or has at least one employee.
</div>

<div class="grid_12 t_a_ui_data_list_header">
	<div class="grid_4 alpha">
		<div>Name</div>
	</div>

	<div class="grid_4">Description</div>

	<div class="grid_2">Lock Status</div>

	<div class="grid_2 omega"># of Employees</div>
</div>

<div class="grid_12 t_a_bottom">        
	<?php foreach ($this->departments as $dept) : ?>
	<div class="clearfix t_a_ui_data_list_content" id="roleRow_<?php echo $dept->dept_id; ?>">
		<div class="grid_4 alpha">
			<div><?php echo $dept->name; ?></div>

			<div class="t_a_top t_a_ui_helper_action">
				<a class="lockAction" rel="<?php echo $dept->dept_id; ?>_<?php echo $dept->is_active; ?>_<?php echo $dept->name; ?>" href="javascript: void(0);"><?php if ($dept->is_active) : ?>Unlock<?php else : ?>Lock<?php endif; ?></a>
                                <?php //@todo check employee number ?>
				<?php  if (!$dept->is_active) : ?> | <a href="/department/update/id/<?php echo $dept->dept_id; ?>">Update</a> | <a class="deleteAction" rel="<?php echo $dept->dept_id; ?>_<?php echo $dept->name; ?>" href="javascript: void(0);">Delete</a><?php endif; ?>
			</div>
		</div>

		<div class="grid_4"><?php echo $dept->description; ?>&nbsp;</div>

		<div class="grid_2"><?php if ($dept->is_active) : ?>Locked<?php else : ?>Unlocked<?php endif; ?></div>

		<div class="grid_2 omega"><?php ?></div>
	</div>
	<?php endforeach; ?>            
</div>
<?php endif; ?>

<div class="grid_12 t_a_bottom">
	<h3>Add New Department</h3>
</div>

<div class="grid_12 t_a_bottom"><hr /></div>

<form method="post" id="addDeptForm" name="addDeptForm" action="<?php echo $this->url(array('controller'=>'department', 'action'=>'add')); ?>">
<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		<div class="clearfix t_a_bottom">
			<label>Name:</label>
			<input type="text" style="width: 200px" name="name" id="name" />
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>Description:</label>
			<input type="text" style="width: 200px" name="description" id="description" />
		</div>

		<hr />

		<div class="clearfix">
			<label>&nbsp;</label>
			<input type="checkbox" name="lock" value="1" /> Lock this Department
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="submit"><span>Create</span></button>
		</div>
	</div>
</div>
</form>

<div id="messageDialog"></div>

<div id="confirmDialog"></div>

<script type="text/javascript">
    $(document).ready(function() {
	$('a.lockAction').click(function() {
		var self = this;
		var arr = $(this).attr('rel').split('_');
		$(self).html('').addClass('t_a_ui_helper_loading');
		$.ajaxq('core_role', {
			url: '<?php echo $this->url(array('controller'=>'department', 'action'=>'lock')); ?>',
			type: 'POST',
			data: { id: arr[0], lock: arr[1] },
			success: function(response) {
				$(self).attr('rel', arr[0] + '_' + response + '_' + arr[2]);
				if (response == 1) {
					$(self).html("Unlock");
				} else {
					$(self).html("Lock");
				}
				$(self).removeClass('t_a_ui_helper_loading');
				$('#messageDialog').html((response == 1) ? sprintf('<?php echo addslashes("Department was successfully locked"); ?>', arr[2]) : sprintf('<?php echo addslashes("Department was successfully unlocked"); ?>', arr[2]))
					.dialog({
						title: '<?php echo addslashes("Notification"); ?>',
						dialogClass: 't_a_ui_dialog',
						modal: true,
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
			}
		});
	});


	$('a.deleteAction').click(function() {
		var self = this;
		$('#confirmDialog').html('<?php echo addslashes("Are you sure you want to delete this department?"); ?>')
			.dialog({
				title: '<?php echo addslashes("Confirm delete"); ?>',
				dialogClass: 't_a_ui_dialog',
				modal: true,
				closeOnEscape: false,
				resizable: false,
				open: function(event, ui) {
					$('.ui-dialog-titlebar-close').hide();
					$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
				},
				buttons: {
					'<?php echo addslashes("No"); ?>': function() {
						$(this).dialog('destroy');
					},
					'<?php echo addslashes("Yes"); ?>': function() {
						$(this).dialog('destroy');
						$(self).html('&nbsp;').addClass('t_a_ui_helper_loading').css('text-decoration', 'none');
						var arr = $(self).attr('rel').split('_');
						$.ajaxq('core_role', {
							url: '<?php echo $this->url(array('controller'=>'department', 'action'=>'delete')); ?>',
							type: 'POST',
							data: { id: arr[0] },
							success: function(response) {
								$('#roleRow_' + arr[0]).fadeOut('slow');
								$('#messageDialog').html(sprintf('<?php echo addslashes("Department was successfully deleted"); ?>', arr[1]))
									.dialog({
										title: '<?php echo addslashes("Notification"); ?>',
										dialogClass: 't_a_ui_dialog',
										modal: true,
								    	show: { effect: 'fade' },
										open: function(event, ui) {
											setTimeout(function() {
												$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											}, 3000);
										}
									});
							}
						});
					}
				}
			});
	});


	/**
	 * Validate form
	 */
	$('#addRoleForm').validate({
		rules: {
			name: {
				required: true
			},
			description: {
				required: true
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo addslashes("The department name is required"); ?>"
			},
			description: {
	        	required: "<?php echo addslashes("The department description is required"); ?>"
			}
		}
	});
});
</script>
