<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Error 404  :: Twiga</title>
        <link rel="stylesheet" href="<?php echo $this->staticUrl('/css/reset.css')?>" />
        <link rel="stylesheet" href="<?php echo $this->staticUrl('/css/twiga.css')?>" />
               
    </head>
    <body>
        <div id="body-container">
            <div id="error-page-container">
                <h1>404 :(</h1>
                <hr>
                <span>Oops! Something went wrong. Requested page not found!</span>
                <a href="<?php echo $this->staticUrl('/')?>">Back to Dashboard</a>
            </div>
        </div>        
    </body>
</html>