<?php 

$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'list')); ?>">List of Users</a></span>
	<span>Add New User</span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'add')); ?>" id="addUserForm">
<div class="grid_12 t_a_bottom">Enter the user information in the form:</div>

<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		<div class="clearfix t_a_bottom">
			<label>Full Name:</label>
			<input type="text" id="full_name" name="full_name" style="width: 200px" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Username:</label>
			<input type="text" id="username" name="username" style="width: 200px" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Password:</label>
			<input type="password" id="password" name="password" style="width: 200px" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Confirm Password:</label>
			<input type="password" id="confirmPassword" name="confirmPassword" style="width: 200px" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Email:</label>
			<input type="text" id="email" name="email" style="width: 200px" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Group:</label>
			<select name="role" id="role">
				<option value="">---</option>
				<?php foreach ($this->roles as $role) : ?>
				<option value="<?php echo $role->role_id; ?>"><?php echo $role->name; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<?php echo $this->tokenElement; ?>
                        <button type="submit"><span>Create User</span></button> or <a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'list'), null, true)?>">Cancel</a>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#addUserForm').validate({
		rules: {
			full_name: {
				required: true
			},
			username: {
		  		required: true,
		  		minlength: 5,
		  		maxlength: 255,
		  		remote: '<?php echo $this->url(array('controller'=>'user','action'=>'check','check_type' => 'username')); ?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('controller'=>'user','action'=>'check','check_type' => 'email')); ?>'
			},
			password: {
		  		required: true,
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			},
			role: {
				required: true
			}
	    },
	    messages: {
	    	full_name: {
	        	required: "Full Name is required"
	    	},
	    	username: {
	        	required: "Username is required",
				minlength: "Username must be at least 5 characters long",
				maxlength: "Username max length",
				remote: "Username is already in use"
			},
			email: { 
	        	required: "Email is required",
	        	email: "Email format is invalid",
		        remote: "Email is already in use"
	    	},
	    	password: {
				required: "Password is required",
				minlength: "Password must be at least 5 characters long"
			},
			confirmPassword: {
				equalTo: "Passwords don not match"
			},
			role: {
				required: "Select a group for the user"
			}
		}
	});
});
</script>
