<?php 
$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>
<div class="grid_12 t_a_ui_breadcrumb">
	<span>Change Password</span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		<form method="post" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'change-password')); ?>" id="changepassForm">
		<div class="t_a_bottom">
			<label>New Password:</label>
			<div>
				<input type="password" style="width: 200px" name="password" id="password" />
				<p>The password must contain at least 5 characters</p>
			</div>
		</div>

		<hr />

		<div class="t_a_bottom">
			<label>Confirm Password:</label>
			<div>
				<input type="password" style="width: 200px" name="confirmPassword" id="confirmPassword" />
				<p>Re-type the password that you have entered above</p>
			</div>
		</div>

		<hr />

		<div class="t_a_bottom">
			<label>&nbsp;</label>
			<?php echo $this->tokenElement; ?>
                        <button type="submit"><span>Change Password</span></button> or <a href="/">Cancel</a>
		</div>
		</form>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#changepassForm').validate({
		rules: {
			password: {
				required: true,
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			}
	    },
	    messages: {
	    	password: {
	    		required: "Password is required",
				minlength: "Password length should be at least 5 characters"
			},
			confirmPassword: {
				equalTo: "Passwords don't match, try again"
			}
		}
	});
});
</script>
