<?php

$this->headLink()
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.core.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.resizable.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.dialog.css'))
	->appendStylesheet($this->staticUrl('/js/jquery.ui/themes/base/ui.theme.css'));

$this->headScript()
	->appendFile($this->staticUrl('/js/jquery.ui/ui.core.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.draggable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.resizable.js'))
	->appendFile($this->staticUrl('/js/jquery.ui/ui.dialog.js'))
	->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span>List of Users</span>
</div>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="grid_9 alpha">You can use following conditions to filter the list of users:</div>

	<div class="grid_3 omega">
		<div class="t_a_right">
			<a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'add')); ?>" class="t_a_ui_button_link"><span>Add New User</span></a>
		</div>
	</div>
</div>

<!-- Filter form -->
<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1" id="filerContainer">
		<div class="clearfix t_a_bottom">
			<div class="grid_5 alpha">
				<label>Username:</label>
				<input type="text" style="width: 180px" name="username" />
			</div>

			<div class="grid_5 omega">
				<label>Role:</label>
				<select name="role" style="width: 180px">
					<option value="">---</option>
					<?php foreach ($this->roles as $role) : ?>
					<option value="<?php echo $role->role_id; ?>"><?php echo $role->name; ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="button" id="filterButton"><span>Filter</span></button>
		</div>
	</div>
</div>

<!-- List of users -->
<?php if (count($this->users) == 0) : ?>
<div class="grid_12 t_a_bottom">There are no users in the system</div>
<?php else : ?>
<div class="grid_12 t_a_bottom">Below is a list of users</div>

<div class="grid_12 t_a_ui_data_list_header">
	<div class="grid_8 alpha">
		<div>Username</div>
	</div>

	<div class="grid_3">Email</div>

	<div class="grid_1 omega">Id</div>
</div>

<div class="grid_12 t_a_bottom">
	<div id="users">
		<?php foreach ($this->paginator as $user) : ?>
		<div class="clearfix t_a_ui_data_list_content" id="roleRow_<?php echo $user->id; ?>">
			<div class="grid_8 alpha">
                            <div><?php echo $user->full_name; ?> &rarr; <?php echo $user->user_name; ?></div>

				<div class="t_a_top t_a_ui_helper_action">
					<a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'update','user_id' => $user->id)); ?>">Update</a>


					<?php if ($user->user_name != $this->currentUser) : ?>
					| <a class="activateAction" rel="<?php echo $user->id; ?>_<?php echo (int)$user->is_active; ?>_<?php echo $user->user_name; ?>" href="javascript: void(0);"><?php if ($user->is_active) : ?>De-Activate<?php else : ?>Activate<?php endif; ?></a>
					| <a class="deleteAction" rel="<?php echo $user->id; ?>_<?php echo (int)$user->is_active; ?>_<?php echo $user->user_name; ?>" href="javascript: void(0);">Delete</a>
                                        <?php endif; ?>
				</div>
			</div>

			<div class="grid_3"><?php echo $user->email; ?></div>

			<div class="grid_1 omega"><?php echo $user->id; ?></div>
		</div>
		<?php endforeach; ?>

		<div class="t_a_bottom t_a_ui_paginator">
			<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
		</div>
	</div>
</div>
<?php endif; ?>

<div id="messageDialog"></div>
<div id="confirmDialog"></div>

<script type="text/javascript">
$(document).ready(function() {
        $('a.deleteAction').click(function() {
		var self = this;
		$('#confirmDialog').html('<?php echo addslashes("Are you sure you want to delete this user?"); ?>')
			.dialog({
				title: '<?php echo addslashes("Confirm"); ?>',
				dialogClass: 't_a_ui_dialog',
				modal: true,
				closeOnEscape: false,
				resizable: false,
				open: function(event, ui) {
					$('.ui-dialog-titlebar-close').hide();
					$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
				},
				buttons: {
					'<?php echo addslashes("No"); ?>': function() {
						$(this).dialog('destroy');
					},
					'<?php echo addslashes("Yes"); ?>': function() {
						$(this).dialog('destroy');
						$(self).html('&nbsp;').addClass('t_a_ui_helper_loading').css('text-decoration', 'none');
						var arr = $(self).attr('rel').split('_');
						$.ajaxq('core_role', {
							url: '<?php echo $this->url(array('controller'=>'user', 'action'=>'delete')); ?>',
							type: 'POST',
							data: { id: arr[0] },
							success: function(response) {
								$('#roleRow_' + arr[0]).fadeOut('slow');
								$('#messageDialog').html(sprintf('<?php echo addslashes("User was successfully deleted"); ?>', arr[1]))
									.dialog({
										title: '<?php echo addslashes("Notification"); ?>',
										dialogClass: 't_a_ui_dialog',
										modal: true,
								    	show: { effect: 'fade' },
										open: function(event, ui) {
											setTimeout(function() {
												$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											}, 3000);
										}
									});
							}
						});
					}
				}
			});
	});
        
	$('#filterButton').click(function() {
		var query = {
			username: $('#filerContainer').find('input[name="username"]:first').attr('value'),			
			role: $('#filerContainer').find('select[name="role"]:first').attr('value'),			
		};
		filterUsers(1, query);
	});

	
	$('a.activateAction').click(function() {
		activateUser(this);
	});
	
});

function filterUsers(page, query) {
	query.pageIndex = page;
	$('#users').html('').addClass('t_a_ui_helper_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array('controller'=>'user', 'action'=>'list')); ?>',
		type: 'POST',
		data: { query: $.toJSON(query) },
		success: function(response) {
			$('#users').html(response).removeClass('t_a_ui_helper_loading').fadeIn('normal');
		}
	});
};


function activateUser(linkObj) {
	var self = linkObj;
	var arr = $(self).attr('rel').split('_');
	$(self).html('').addClass('t_a_ui_helper_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array('controller'=>'user', 'action'=>'change-status')); ?>',
		type: 'POST',
		data: { id: arr[0], status: arr[1] },
		success: function(response) {
			$(self).attr('rel', arr[0] + '_' + response + '_' + arr[2]);
			if (response == 1) {
				$(self).html("De Activate");
			} else {
				$(self).html("Activate");
			}
			$(self).removeClass('t_a_ui_helper_loading').fadeIn('normal');

			$('#messageDialog').html((response == 1) ? sprintf('<?php echo addslashes('User was successfully activated'); ?>', arr[2]) : sprintf('<?php echo addslashes('User was successfully de-activated'); ?>', arr[2]))
				.dialog({
					title: '<?php echo addslashes('Notification'); ?>',
					dialogClass: 't_a_ui_dialog',
					modal: true,
			    	show: { effect: 'fade' },
					open: function(event, ui) {
						setTimeout(function() {
							$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
						}, 3000);
					}
				});
		}
	});
};

</script>
