<?php 

$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'list')); ?>">List of Users</a></span>
	<span>Edit User <?php echo $this->user->full_name; ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<div class="grid_12 t_a_bottom">Enter new information about the user in the form below:</div>

<form method="post" action="<?php echo $this->url(array('controller'=>'user','action'=>'update')); ?>" id="editUserForm">
<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
		<div class="clearfix t_a_bottom">
			<label>Full Name:</label>
			<input type="text" style="width: 200px" name="full_name" id="full_name" value="<?php if (null != $this->user && null != $this->user->full_name) : ?><?php echo $this->user->full_name; ?><?php endif; ?>" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Username:</label>
			<input type="text" style="width: 200px" name="username" id="username" value="<?php if (null != $this->user && null != $this->user->user_name) : ?><?php echo $this->user->user_name; ?><?php endif; ?>" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Password:</label>
			<input type="password" style="width: 200px" name="password" id="password" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Confirm Password:</label>
			<input type="password" style="width: 200px" name="confirmPassword" id="confirmPassword" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Email:</label>
			<input type="text" style="width: 200px" name="email" id="email" value="<?php if (null != $this->user && null != $this->user->email) : ?><?php echo $this->user->email; ?><?php endif; ?>" />
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>Role:</label>
			<select name="role">
				<?php foreach ($this->roles as $role) : ?>
				<option value="<?php echo $role->role_id; ?>" <?php if ($this->user != null && $this->user->role_id == $role->role_id) : ?> selected<?php endif; ?>><?php echo $role->name; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		
		<hr />
		
		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>	
			<button type="submit"><span>Save Changes</span></button>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#editUserForm').validate({
		rules: {
		    full_name: {
				required: true
			},
			username: {
		  		required: true,
		  		minlength: 5,
		  		maxlength: 255,
		  		remote: '<?php echo $this->url(array('controller'=>'user','action'=>'check','check_type' => 'username')); ?>?original=<?php echo $this->user->user_name; ?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('controller'=>'user','action'=>'check','check_type' => 'email')); ?>?original=<?php echo $this->user->email; ?>'
			},
			password: {
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			},
			role: {
				required: true
			}
	    },
	    messages: {
	    	full_name: {
	        	required: "Full names are required"
	    	},
	    	username: {
	        	required: "Username is required",
				minlength: "Username must be at least",
				maxlength: "Max username",
				remote: "Username has been taken"
			},
			email: { 
				required: "Email is required",
	        	email: "Email is invalid",
		        remote: "Email already exists"
	    	},
	    	password: {
	    		minlength: "Password must be at least 5 characters"
			},
			confirmPassword: {
				equalTo: "Passwords do not match"
			},
			role: {
				required: "Please choose a User Role"
			}
		}
	});
});
</script>
