<?php

$this->headScript()->appendFile($this->staticUrl('/js/jquery.validate/jquery.validate.min.js'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span><a href="<?php echo $this->url(array('controller'=>'job-title', 'action'=>'list')); ?>">List of Job Titles</a></span>
	<span>Edit Job Title <?php echo $this->job_title->name; ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('controller'=>'job-title', 'action'=>'update')); ?>" id="editJobTitleForm">
<div class="grid_12 t_a_bottom">Update Job Title Information as necessary:</div>

<div class="grid_12 t_a_bottom">
	<div class="prefix_1 suffix_1">
            <input type="hidden" name="id" value="<?php echo $this->job_title->id; ?>" />
		<div class="clearfix t_a_bottom">
			<label>Name:</label>
			<input type="text" style="width: 200px" name="name" id="name" value="<?php echo $this->job_title->name; ?>"/>
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>Description:</label>
			<input type="text" style="width: 200px" name="description" id="description" value="<?php echo $this->job_title->description; ?>" />
		</div>

		<hr />

		<div class="clearfix">
			<label>&nbsp;</label>
			<input type="checkbox" name="lock" value="<?php echo $this->job_title->is_active; ?>" <?php if($this->job_title->is_active == 1) {echo ' checked="checked"'; } ?> /> Lock this Job Title
		</div>

		<hr />

		<div class="clearfix t_a_bottom">
			<label>&nbsp;</label>
			<button type="submit"><span>Save Changes</span></button> or <a href="<?php echo $this->url(array('controller'=>'job-title', 'action'=>'list'), null, true)?>">Cancel</a>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#editJobTitleForm').validate({
		rules: {
			name: {
				required: true
			},
			description: {
				required: true
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo addslashes("The job title name is required"); ?>"
			},
			description: {
	        	required: "<?php echo addslashes("The job title description is required"); ?>"
			}
		}
	});
});
</script>
